### ISSUE TITLE
plugin downloads wrong architecture for macOS M1

### ISSUE THREAD

**Issue by vewert** [openjfx/javafx-gradle-plugin#112] opened 2021-09-11 22:38 UTC
I'm running on macOS with a Silicon (M1) chip.

I set the version in the plugin to 17, which should download openjfx 17, which has M1 support.

When I run my application, I get the following error:

```
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/vewert/.openjfx/cache/17/libprism_es2.dylib: dlopen(/Users/vewert/.openjfx/cache/17/libprism_es2.dylib, 1): no suitable image found.  Did find:
	/Users/vewert/.openjfx/cache/17/libprism_es2.dylib: mach-o, but wrong architecture
	/Users/vewert/.openjfx/cache/17/libprism_es2.dylib: stat() failed with errno=38
```

I checked `/Users/vewert/.openjfx/cache/17/` and ran `file libprism_es2.dylib` and got: `libprism_es2.dylib: Mach-O 64-bit dynamically linked shared library x86_64` which makes it look like it has downloaded the Intel libraries instead of the M1 libraries.

I'm not sure if the problem is that the M1 version isn't available on Maven Central, or the plugin is downloading the wrong one.

As a work around, I downloaded the JavaFX 17 jdk, set a local sdk: https://github.com/openjfx/javafx-gradle-plugin#5-using-a-local-javafx-sdk

**Comment by strazdinsg** [comment] 2021-09-20 15:49
I get the same problem when using Maven

**Comment by EdwardZeed** [comment] 2021-10-31 03:48
I saw the issue is closed, but I'm still getting the same problem. I'm using apple silicon and it seems like the libraries I got is based on x86.
here is what I had in my build script.
`plugins {
    // Apply the java plugin to add support for Java
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.0.10'
    // Apply the application plugin to add support for building an application
    id 'application'
}


javafx {
    version = "17"
    modules = [ 'javafx.controls', 'javafx.media' ]
}`

**Comment by hohonuuli** [comment] 2021-11-15 23:40
@henryhchchc Thanks for addressing this

Anyone have a timeline when this a new release with this fix will be published?

**Comment by mbcoder** [comment] 2021-12-21 16:35
Looks like this fix will be part of 0.0.11 - do you know when this will be released?

**Comment by GordonGgx** [comment] 2021-12-24 11:17
> Looks like this fix will be part of 0.0.11 - do you know when this will be released?

I get the same problem .How did you solve it

**Comment by cryptoAlgorithm** [comment] 2022-04-10 03:28
In `build.gradle` change the javafx plugin version to `0.0.11` or above, for example:

```gradle
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.11'
}
```

**Comment by FeldrinH** [comment] 2022-09-28 12:37
Is this issue resolved?

**Comment by vewert** [comment] 2022-09-28 15:37
This seems to be working for me, I am currently using version 0.0.13.

**Closed** 2023-09-06 20:02 UTC
