### ISSUE TITLE
Plugin should not add dependencies in afterEvaluate

### ISSUE THREAD

**Issue by lenborje** [openjfx/javafx-gradle-plugin#16] opened 2018-12-06 09:42 UTC
When running in a gradle multi-project, the build will fail with an error similar to the following:

    A problem occurred configuring project ':Base'.
    > Cannot change dependencies of configuration ':Base:compile' after it has been included in dependency resolution.

This is caused by the plugin modifying the dependencies in the `afterEvaluate` project method.

I have resolved this issue in a fork and submitted a pull request, q.v.:

[Pull request #15](https://github.com/openjfx/javafx-gradle-plugin/pull/15)

**Comment by tiainen** [comment] 2018-12-07 18:51
I have applied the plugin in a multi-project setup and it ran fine without any issues. This makes me think that the issue is not specifically related to multi-project structures.

This issue arises because some code triggered the declared dependencies to be resolved. Once that is done, you can no longer change the project dependencies, resulting in the error you mention. Can you provide a project that reproduces the error? I'm not sure yet if the proposed solution is the best one.

**Comment by lenborje** [comment] 2018-12-07 23:08
The failure depends on the order of project dependencies.

Let’s assume you have two projects, A and B, where B depends on A.

It will fail if A uses the plugin. 
It runs OK if B (and only B) uses the plugin. 

I can provide a minimal example on Monday.

**Comment by lenborje** [comment] 2018-12-10 10:38
OK, you're right. I've trimmed down my own project to a minimum where the problem is triggered, and that is actually not a multi-project.

It **is** triggered by anything referring to the `configurations` property.

Steps to reproduce:

1. Check out the HelloFX sample repo [https://github.com/openjfx/samples.git](https://github.com/openjfx/samples.git).
2. Go to the `samples/HelloFX/Gradle/hellofx` directory.
3. Add the following line to `build.gradle`:

```System.out.println(configurations.runtime.collect{it.name})```

Gradle will now fail, e.g.:

    $ ./gradlew run
    Parallel execution is an incubating feature.
    
    > Configure project :
    []
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    A problem occurred configuring root project 'hellofx'.
    > Cannot change dependencies of configuration ':compile' after it has been included in dependency resolution.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 0s

Switching to my fork (version 0.0.6-SNAPSHOT) will restore expected behaviour.

**Comment by tiainen** [comment] 2018-12-13 08:59
Fixed with #15.

**Closed by tiainen** 2018-12-13 08:59 UTC
